# Generated by Django 4.0.5 on 2022-07-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_category_name_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
